document.writeln('<div class="container-fluid">')
document.writeln('    <div class="row col-md-3 col-xs-3 col-sm-3">')
document.writeln('        <div class="span8">')
document.writeln('        <font size="5">')
document.writeln('            <ul class="nav nav-tabs nav-stacked">')
document.writeln('                <li id="allFacilities" ><a href="./listAll">所有设备</a></li>')
document.writeln('                <li id="addFacility"><a href="./addFacility">添加设备</a></li>')
document.writeln('                <li id="agentInfo"><a href="#">物管理器信息</a></li>')
document.writeln('                <li id="deleteFacility"><a href="#">删除设备</a></li>')
document.writeln('                <li id="manage"><a href="#">设备管理</a></li>')
document.writeln('            </ul>')
document.writeln('        </div>')
document.writeln('    </div>')
document.writeln('    <div class="row col-md-6 col-xs-9 col-sm-9">')
