document.writeln('<div class="container">')
document.writeln('    <div class="row col-md-4 col-xs-3 col-sm-3">')
document.writeln('        <div class="span8">')
document.writeln('            <ul class="nav nav-tabs nav-stacked">')
document.writeln('                <li class="active"><a href="#">Home</a></li>')
document.writeln('                <li><a href="#">Tutorials</a></li>')
document.writeln('               <li><a href="#">Practice Editor </a></li>')
document.writeln('                <li><a href="#">Gallery</a></li>')
document.writeln('                <li><a href="#">Contact</a></li>')
document.writeln('            </ul>')
document.writeln('        </div>')
document.writeln('    </div>')
document.writeln('    <div class="row col-md-6 col-xs-9 col-sm-9">')
